version: '3'

services:
  decidim-postgres:
    image: postgres
    container_name: decidim-postgres
    environment:
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - decidim

  decidim-ubuntu:
    image: usbing/decidim:1.0
    container_name: decidim-ubuntu
    command: sh -c "sudo nginx -g 'daemon off;'"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - decidim-data:/home/decidim/decidim-app/storage
    working_dir: /home/decidim
    networks:
      - decidim
    
networks:
  decidim:
    external: true

volumes:
  pg-data:
  decidim-data: